
--
-- Table structure for table FORMER
--

CREATE TABLE FORMER (
  FORMER_ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FARMERS_NAME varchar(250) NOT NULL,
  PHONE_NUMBER int(10) NOT NULL,
  AADHAR_NUMBER int(11) NOT NULL,
  SHARE_AMOUNT int(11) DEFAULT NULL,
  GENDER varchar(10) NOT NULL,
  CASTE varchar(250) DEFAULT NULL,
  EDUCATION varchar(250) DEFAULT NULL,
  BANK_IFSC_CODE varchar(20) DEFAULT NULL,
  TOTAL_LAND_HOLDING int(11) DEFAULT NULL,
  HOUSE_HOLD_SIZE int(11) DEFAULT NULL,
  MODIFIED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MODIFIED_BY varchar(250) NOT NULL,
  CREATED_DATE timestamp NOT NULL,
  CREATED_BY varchar(250) NOT NULL
) ENGINE=InnoDB;

COMMIT;