
--
-- Table structure for table FORMER
--

CREATE TABLE FORMER (
  FORMER_ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FPO_ID int(11) NOT NULL,
  DISTRICT varchar(250) NOT NULL,
  VILLAGE_ID int(11) NOT NULL,
  FIG_ID int(11) NOT NULL,
  FARMERS_NAME varchar(250) NOT NULL,
  PHONE_NUMBER int(10) NOT NULL,
  AADHAR_NUMBER int(11) NOT NULL,
  SHARE_AMOUNT int(11) DEFAULT NULL,
  GENDER varchar(10) NOT NULL,
  CASTE varchar(250) DEFAULT NULL,
  EDUCATION varchar(250) DEFAULT NULL,
  BANK_IFSC_CODE varchar(20) DEFAULT NULL,
  TOTAL_LAND_HOLDING int(11) DEFAULT NULL,
  HOUSE_HOLD_SIZE int(11) DEFAULT NULL,
  MODIFIED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MODIFIED_BY varchar(250) NOT NULL,
  CREATED_DATE timestamp NOT NULL,
  CREATED_BY varchar(250) NOT NULL,
   FOREIGN KEY FK_FPO(FPO_ID)
   REFERENCES FPO(FPO_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT,
   FOREIGN KEY FK_VILLAGE(VILLAGE_ID)
   REFERENCES VILLAGE(VILLAGE_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT,
   FOREIGN KEY FK_FIG(FIG_ID)
   REFERENCES FIG(FIG_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT
) ENGINE=InnoDB;

COMMIT;